---
- name: "10s delay while starting Jenkins"
  wait_for: host=localhost port={{ jenkins.port }} delay=10
  when: jenkins_installed.changed or config_changed.changed

- name: Get Jenkins CLI
  get_url: url=http://localhost:{{ jenkins.port }}/jnlpJars/jenkins-cli.jar dest={{ jenkins.cli }} mode=0440
  register: jenkins_local_cli
  until: "'OK' in jenkins_local_cli.msg or 'file already exists' in jenkins_local_cli.msg"
  retries: 5
  delay: 10

- name: Get Jenkins updates
  get_url: url=https://updates.jenkins-ci.org/update-center.json dest={{ jenkins.updates }} thirsty=yes mode=0440 timeout=30
  register: jenkins_updates

- name: Update-center Jenkins
  shell: "cat {{ jenkins.updates }} | sed '1d;$d' | curl -X POST -H 'Accept: application/json' -d @- http://localhost:{{ jenkins.port }}/updateCenter/byId/default/postBack"
  when: jenkins_updates.changed
  notify: Restart Jenkins
