---
# The playbook for Ant tasks. From https://github.com/AdesisNetlife/ansible-jenkins

- name: Download Ant
  get_url: url=http://www.eu.apache.org/dist/ant/binaries/apache-ant-{{ ant_version }}-bin.tar.gz dest=/tmp/apache-ant-{{ ant_version }}-bin.tar.gz mode=0555

- name: Unarchive the compressed Ant binaries
  shell: cd /tmp && tar vxf apache-ant-{{ ant_version }}-bin.tar.gz && mv apache-ant-{{ ant_version }} /usr/local/apache-ant-{{ ant_version }}

- name: Update the symbolic link to the Ant install
  file: "path=/usr/local/ant src=/usr/local/apache-ant-{{ ant_version }} state=link force=yes"

- name: Set ANT_HOME environment variable
  lineinfile: dest=/etc/environment regexp='^ANT_HOME.*' line='ANT_HOME=/usr/local/ant' insertbefore='^PATH.*'

- name: Add Ant binaries to PATH environment variable
  lineinfile: dest=/etc/environment state=present backrefs=yes regexp='PATH=(["]*)((?!.*?/usr/local/ant/bin).*?)(["]*)$' line="PATH=\1\2:/usr/local/ant/bin\3"
