---
- name: Install Nginx
  apt: pkg=nginx state=latest

- name: Install php5-fpm
  apt: pkg=php5-fpm state=latest

- name: Change default nginx site
  template: src=default.tpl dest=/etc/nginx/sites-available/default
  notify: restart nginx

- name: Install PHP Packages
  apt: pkg={{ item }} state=latest
  with_items: php_packages

- name: Install PHP Autoload Builder
  get_url: url=https://github.com/theseer/Autoload/releases/download/{{ phpab_version }}/phpab-{{ phpab_version }}.phar dest=/usr/bin/phpab mode=0555