---
- name: Restart Jenkins
  command: java -jar {{ jenkins.cli }} -s http://localhost:{{ jenkins.port }} safe-restart

- name: Reload Configuration
  command: java -jar {{ jenkins.cli }} -s http://localhost:{{ jenkins.port }} reload-configuration